[workspace]
resolver = "2"
members = ["services/*", "libs/*"]
default-members = ["services/*", "libs/*"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
hyper = "0.14.27"
rand = "0.8.5"
