version: '3.8'

services:
  instance1:
    image: raft_mingle:latest
    environment:
      - PORT=8001
    ports:
      - "8001:8001"

  instance2:
    image: raft_mingle:latest
    environment:
      - PORT=8002
    ports:
      - "8002:8002"

  instance3:
    image: raft_mingle:latest
    environment:
      - PORT=8003
    ports:
      - "8003:8003"
